name: CICD Pipeline

env:
  DEV_URI: localhost
  REQ_PATH: ./src/app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cicd:
    name: CICD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check path
        run: |
          ls -alt
          pwd

      - name: Set up Python 3.6
        uses:  actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install flake8 pytest requests pytest-bdd
          ls -alt
          pip3 install -r $REQ_PATH/requirements.txt

      - name: TDD
        run: |
          make tdd


