name: CICD

env:
  DEV_URI: localhost

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cicd:
    name: CICD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check path
        run: |
          ls -alt
          pwd

      - name: Set up Python 3.6
        uses:  actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 pytest requests python-bdd
          if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi

      - name: TDD
        run: |
          cd tests
          make tdd
          cd ..
          ls -alt
          pwd


