name: CICD Pipeline

env:
  REQ_PATH: ./src/app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cicd:
    name: CICD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sanity check for path
        run: |
          ls

      - name: Set up Python 3.6
        uses:  actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install flake8 pytest requests pytest-bdd behave
          if [ -f $REQ_PATH/requirements.txt ]; then pip3 install -r $REQ_PATH/requirements.txt; fi

      - name: TDD Tests
        run: |
          make tdd

      - name: Configure AWS credentials
        run: |
          echo "fill in configuration"

      - name: Login to Amazon ECR
        run: |
          echo "fill in login"

      - name: Docker build and push to dev
        run: |
          echo "fill in build steps"

      - name: Update task definition dev
        run: |
          echo "fill in update task def step"

      - name: Deploy Amazon ECS task definition dev
        run: |
          echo "fill in deploy task def step"

      - name: BDD Tests
        run: |
          export TEST=${{ secrets.URI }}
          make bdd

      - name: Docker build and push to prod
        run: |
          echo "fill in prod build docker step"

      - name: Update task definition prod
        run: |
          echo "fill in prod task def"

      - name: Deploy Amazon ECS task definition prod
        run: |
          echo "fill in prod deploy task def"

      - name: Finished CICD PIPELINE
        run: |
          echo "All services should be updated in prod and dev"